"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "ar" | "ur";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Language names always in their own native script — never translated
export const NATIVE_LANGUAGE_NAMES: Record<Language, string> = {
  en: "English",
  ar: "العربية",
  ur: "اردو",
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    dashboard: "Dashboard",
    users: "Users",
    vehicles: "Vehicles",
    maintenance: "Maintenance",
    reports: "Reports",
    settings: "Settings",
    "sign out": "Sign out",
    // FMAC branding — never translated
    "fmac fleet": "FMAC Fleet",

    // Language
    language: "Language",
    "language desc": "Select the language for the dashboard interface.",
    "ltr layout": "LTR Layout",
    "rtl layout": "RTL Layout",

    // System/Settings
    "system settings": "System Settings",
    "save changes": "Save Changes",
    saving: "Saving...",
    "profile settings": "Profile Settings",
    "full name": "Full Name",
    "email address": "Email Address",
    "name synced": "Your name is synchronized with your account.",
    "primary email": "Your primary contact email.",
    role: "Role",
    notifications: "Notifications",
    cancel: "Cancel",
    administrator: "Administrator",
    driver: "Driver",

    // Auth
    "sign in title": "Sign in to your account",
    "welcome back": "Welcome back",
    "login desc": "Enter your credentials to access the fleet.",
    email: "Email",
    password: "Password",
    "confirm password": "Confirm Password",
    "signing in": "Signing in...",
    "sign in": "Sign in",
    "no account": "Don't have an account?",
    "sign up": "Sign up",
    "already account": "Already have an account?",
    "log in": "Log in",
    register: "Register",
    "register desc": "Enter details to request fleet access.",
    creating: "Creating...",
    "create account": "Create Account",
    "preferred language": "Preferred Language",
    "preferred language desc": "Your language preference will be applied each time you log in.",
    "password min 6": "Password must be at least 6 characters.",
    "passwords no match": "Passwords do not match.",
    "invalid credentials": "Invalid email or password.",

    // Vehicles
    "fleet vehicles": "Fleet Vehicles",
    "fleet vehicles desc": "Manage company cars and buses.",
    "register vehicle": "Register New Vehicle",
    "register vehicle desc": "Enter details to add a vehicle to the fleet.",
    "add vehicle": "Add Vehicle",
    "save vehicle": "Save Vehicle",
    "plate number": "Plate Number",
    "make and model": "Make & Model",
    "vehicle type": "Vehicle Type",
    "initial odometer": "Initial Odometer (km)",
    status: "Status",
    odometer: "Odometer",
    actions: "Actions",
    active: "Active",
    "in maintenance": "In Maintenance",
    "out of service": "Out of Service",
    "no vehicles": "No vehicles registered yet.",
    "delete vehicle confirm": "Are you sure you want to delete this vehicle? Actions cannot be undone.",
    "failed add vehicle": "Failed to add vehicle (Plate number might not be unique).",
    "failed delete": "Failed to delete.",
    "failed update status": "Failed to update status.",
    "failed update odometer": "Failed to update odometer.",
    "edit odometer prompt": "Enter the correct odometer reading (km):",
    "invalid odometer": "Please enter a valid positive number.",
    "type car": "Car",
    "type bus": "Bus",
    "bus id": "Bus ID",
    "last driven by": "Last Driven By",

    // Maintenance
    "maintenance records": "Maintenance & Records",
    "maintenance records desc": "Corrective actions and monthly billing.",
    "maintenance logs": "Maintenance Logs",
    "monthly statements": "Monthly Statements",
    "log maintenance": "Log Servicing",
    "log maint entry": "Log Maintenance Entry",
    "log maint desc": "Record corrective maintenance performed on a vehicle.",
    "select vehicle": "Select Vehicle",
    "select vehicle placeholder": "-- Select a vehicle --",
    "description of work": "Description of Work",
    "cost optional": "Cost (Optional)",
    "save log": "Save Log & Send Alert",
    "upload statement": "Upload Statement",
    "upload monthly": "Upload Monthly Statement",
    "upload monthly desc": "Archive PDF bills from the garage.",
    "month year": "Month / Year",
    "statement file": "Statement File (PDF/Excel)",
    "upload file": "Upload File",
    "no maintenance": "No maintenance logs found.",
    "no statements": "No statements uploaded.",
    date: "Date",
    vehicle: "Vehicle",
    cost: "Cost",
    "failed create record": "Failed to create record.",
    "failed upload": "Failed to upload statement.",

    // Users
    "user management": "User Management",
    "user management desc": "Approve new signups and assign administrative privileges.",
    user: "User",
    contact: "Contact",
    joined: "Joined",
    "status col": "Status",
    "role col": "Role",
    "access control": "Access Control",
    approved: "Approved",
    pending: "Pending",
    "pending approval": "Pending Approval",
    "pending desc": "Your account has been created and is awaiting administrator approval. Please contact your fleet manager to activate your access.",
    "refresh status": "Refresh Status",
    approve: "Approve",
    revoke: "Revoke",
    "no users": "No users found.",
    you: "You",
    "role change confirm": "Are you sure you want to change this user's role to",

    // Dashboard
    overview: "Overview",
    "overview desc": "Real-time metrics for the FMAC fleet.",
    "total vehicles": "Total Vehicles",
    "vehicles active": "Active",
    "in maintenance count": "In Maintenance",
    "requires attention": "Requires attention",
    "out of service count": "Out of Service",
    "inactive vehicles": "Inactive vehicles",
    "distance 7d": "Distance (7d)",
    "across all": "Across all active vehicles",
    "mileage trend": "Mileage Trend",
    "mileage trend desc": "Distance traversed over the past 7 days",
    "recent activity": "Recent Activity",
    "no recent activity": "No recent activity.",
    "trip logged": "Trip Logged",
    "maintenance recorded": "Maintenance Recorded",
    "unknown vehicle": "Unknown Vehicle",

    // Driver dashboard
    "log new trip": "Log New Trip",
    "log new trip desc": "Select a vehicle and enter your post-trip details.",
    "trip details": "Trip Details",
    "trip details desc": "All fields except notes are required.",
    "trip type": "Trip Type",
    "internal trip": "Internal (Club Transport)",
    "external trip": "External (Tournaments/Events)",
    "start odometer": "Start Odometer",
    "end odometer": "End Odometer",
    "calculated distance": "Calculated Distance:",
    "notes optional": "Notes (Optional)",
    "notes placeholder": "Destination, purpose, or issues...",
    submitting: "Submitting...",
    "submit trip": "Submit Trip Log",
    "trip success": "Trip logged successfully!",
    "error end odo": "End odometer cannot be less than start odometer.",
    "error select vehicle": "Please select a vehicle.",

    // Driver history
    "trip history": "Trip History",
    "trip history desc": "View all your previously logged trips.",
    "no trips": "You haven't logged any trips yet.",
    "start odo": "Start Odo",
    "end odo": "End Odo",

    // Reports
    "reports exports": "Reports & Exports",
    "reports desc": "Browse, filter, and download fleet records.",
    "trip logs": "Trip Logs",
    "all vehicles": "All Vehicles",
    "from date": "From",
    "to date": "To",
    clear: "Clear",
    excel: "Excel",
    pdf: "PDF",
    "no trip records": "No trip records match your filters.",
    "no maint records": "No maintenance records match your filters.",
    plate: "Plate",
    "type col": "Type",
    "start odo col": "Start Odo",
    "end odo col": "End Odo",
    distance: "Distance",
    "failed export": "Failed to export.",
    download: "Download",

    // Behavior
    behavior: "Behavior",
    "behavior desc": "Vehicle driving performance and safety intelligence.",
    "fleet behavior": "Fleet Behavior Intelligence",
    scoreboard: "Vehicle Scoreboard",
    score: "Score",
    "total km": "Total KM",
    braking: "Braking",
    acceleration: "Acceleration",
    cornering: "Cornering",
    speeding: "Speeding",
    violations: "Violations",
    "violation type": "Violation Type",
    "all types": "All Types",
    "risk level": "Risk Level",
    "high risk": "High Risk",
    "medium risk": "Medium Risk",
    "low risk": "Low Risk",
    "upload csv": "Upload CSV",
    "export behavior": "Export Behavior Data",
    "most frequent violation": "Most Frequent Violation",
    "avg fleet score": "Avg Fleet Score",
    "high risk vehicles": "High Risk Vehicles",
    "csv upload success": "Data uploaded and deduplicated successfully!",
    "csv upload failed": "Failed to process CSV file.",
    "rows per page": "Rows per page",
    prev: "Prev",
    next: "Next",
    "violation distribution": "Violation Distribution",
    "violation trends": "Violation Trends",
    "performance profile": "Fleet Performance Profile",
  },

  ar: {
    // Nav
    dashboard: "لوحة القيادة",
    users: "المستخدمين",
    vehicles: "المركبات",
    maintenance: "الصيانة",
    reports: "التقارير",
    settings: "الإعدادات",
    "sign out": "تسجيل الخروج",
    "fmac fleet": "FMAC Fleet",

    // Language
    language: "اللغة",
    "language desc": "اختر لغة واجهة لوحة التحكم.",
    "ltr layout": "تخطيط من اليسار لليمين",
    "rtl layout": "تخطيط من اليمين لليسار",

    // System/Settings
    "system settings": "إعدادات النظام",
    "save changes": "حفظ التغييرات",
    saving: "جارٍ الحفظ...",
    "profile settings": "إعدادات الملف الشخصي",
    "full name": "الاسم الكامل",
    "email address": "البريد الإلكتروني",
    "name synced": "اسمك متزامن مع حسابك.",
    "primary email": "بريدك الإلكتروني الأساسي.",
    role: "الدور",
    notifications: "الإشعارات",
    cancel: "إلغاء",
    administrator: "مسؤول",
    driver: "سائق",

    // Auth
    "sign in title": "تسجيل الدخول إلى حسابك",
    "welcome back": "مرحباً بعودتك",
    "login desc": "أدخل بياناتك للوصول إلى الأسطول.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    "confirm password": "تأكيد كلمة المرور",
    "signing in": "جارٍ تسجيل الدخول...",
    "sign in": "تسجيل الدخول",
    "no account": "ليس لديك حساب؟",
    "sign up": "إنشاء حساب",
    "already account": "هل لديك حساب بالفعل؟",
    "log in": "تسجيل الدخول",
    register: "تسجيل",
    "register desc": "أدخل التفاصيل لطلب الوصول إلى الأسطول.",
    creating: "جارٍ الإنشاء...",
    "create account": "إنشاء حساب",
    "preferred language": "اللغة المفضلة",
    "preferred language desc": "سيتم تطبيق تفضيل اللغة في كل مرة تسجل الدخول.",
    "password min 6": "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
    "passwords no match": "كلمتا المرور غير متطابقتين.",
    "invalid credentials": "بريد إلكتروني أو كلمة مرور غير صحيحة.",

    // Vehicles
    "fleet vehicles": "مركبات الأسطول",
    "fleet vehicles desc": "إدارة سيارات وحافلات الشركة.",
    "register vehicle": "تسجيل مركبة جديدة",
    "register vehicle desc": "أدخل التفاصيل لإضافة مركبة إلى الأسطول.",
    "add vehicle": "إضافة مركبة",
    "save vehicle": "حفظ المركبة",
    "plate number": "رقم اللوحة",
    "make and model": "الماركة والموديل",
    "vehicle type": "نوع المركبة",
    "initial odometer": "قراءة العداد الأولية (كم)",
    status: "الحالة",
    odometer: "عداد المسافة",
    actions: "الإجراءات",
    active: "نشطة",
    "in maintenance": "قيد الصيانة",
    "out of service": "خارج الخدمة",
    "no vehicles": "لم يتم تسجيل أي مركبات بعد.",
    "delete vehicle confirm": "هل أنت متأكد من حذف هذه المركبة؟ لا يمكن التراجع عن هذا الإجراء.",
    "failed add vehicle": "فشل إضافة المركبة (قد يكون رقم اللوحة مكرراً).",
    "failed delete": "فشل الحذف.",
    "failed update status": "فشل تحديث الحالة.",
    "failed update odometer": "فشل تحديث القراءة.",
    "edit odometer prompt": "أدخل قراءة عداد المسافة الصحيحة (كم):",
    "invalid odometer": "يرجى إدخال رقم صحيح وموجب.",
    "type car": "سيارة",
    "type bus": "حافلة",
    "bus id": "معرف الحافلة",
    "last driven by": "آخر سائق",

    // Maintenance
    "maintenance records": "الصيانة والسجلات",
    "maintenance records desc": "الإجراءات التصحيحية والفواتير الشهرية.",
    "maintenance logs": "سجلات الصيانة",
    "monthly statements": "الكشوفات الشهرية",
    "log maintenance": "تسجيل عملية صيانة",
    "log maint entry": "إدخال سجل الصيانة",
    "log maint desc": "تسجيل الصيانة التصحيحية التي أُجريت على مركبة.",
    "select vehicle": "اختر المركبة",
    "select vehicle placeholder": "-- اختر مركبة --",
    "description of work": "وصف العمل",
    "cost optional": "التكلفة (اختياري)",
    "save log": "حفظ السجل وإرسال تنبيه",
    "upload statement": "رفع كشف حساب",
    "upload monthly": "رفع كشف شهري",
    "upload monthly desc": "أرشفة فواتير PDF من الورشة.",
    "month year": "الشهر / السنة",
    "statement file": "ملف الكشف (PDF/Excel)",
    "upload file": "رفع الملف",
    "no maintenance": "لم يتم العثور على سجلات صيانة.",
    "no statements": "لم يتم رفع أي كشوفات.",
    date: "التاريخ",
    vehicle: "المركبة",
    cost: "التكلفة",
    "failed create record": "فشل إنشاء السجل.",
    "failed upload": "فشل رفع الكشف.",

    // Users
    "user management": "إدارة المستخدمين",
    "user management desc": "الموافقة على التسجيلات الجديدة وتعيين الصلاحيات.",
    user: "المستخدم",
    contact: "التواصل",
    joined: "تاريخ الانضمام",
    "status col": "الحالة",
    "role col": "الدور",
    "access control": "التحكم في الوصول",
    approved: "موافق عليه",
    pending: "قيد الانتظار",
    "pending approval": "قيد الانتظار للموافقة",
    "pending desc": "لقد تم إنشاء حسابك وهو في انتظار موافقة المسؤول. يرجى الاتصال بمدیر الأسطول لتفعيل وصولك.",
    "refresh status": "تحديث الحالة",
    approve: "موافقة",
    revoke: "إلغاء الوصول",
    "no users": "لم يتم العثور على مستخدمين.",
    you: "أنت",
    "role change confirm": "هل أنت متأكد من تغيير دور هذا المستخدم إلى",

    // Dashboard
    overview: "نظرة عامة",
    "overview desc": "مقاييس فورية لأسطول FMAC.",
    "total vehicles": "إجمالي المركبات",
    "vehicles active": "نشطة",
    "in maintenance count": "قيد الصيانة",
    "requires attention": "تحتاج إلى اهتمام",
    "out of service count": "خارج الخدمة",
    "inactive vehicles": "مركبات غير نشطة",
    "distance 7d": "المسافة (7 أيام)",
    "across all": "عبر جميع المركبات النشطة",
    "mileage trend": "اتجاه المسافة",
    "mileage trend desc": "المسافة المقطوعة خلال الـ7 أيام الماضية",
    "recent activity": "النشاط الأخير",
    "no recent activity": "لا يوجد نشاط أخير.",
    "trip logged": "تم تسجيل رحلة",
    "maintenance recorded": "تم تسجيل صيانة",
    "unknown vehicle": "مركبة غير معروفة",

    // Driver dashboard
    "log new trip": "تسجيل رحلة جديدة",
    "log new trip desc": "اختر المركبة وأدخل تفاصيل الرحلة.",
    "trip details": "تفاصيل الرحلة",
    "trip details desc": "جميع الحقول مطلوبة ما عدا الملاحظات.",
    "trip type": "نوع الرحلة",
    "internal trip": "داخلية (نقل النادي)",
    "external trip": "خارجية (بطولات/فعاليات)",
    "start odometer": "عداد البداية",
    "end odometer": "عداد النهاية",
    "calculated distance": "المسافة المحسوبة:",
    "notes optional": "ملاحظات (اختياري)",
    "notes placeholder": "الوجهة، الغرض، أو المشكلات...",
    submitting: "جارٍ الإرسال...",
    "submit trip": "إرسال سجل الرحلة",
    "trip success": "تم تسجيل الرحلة بنجاح!",
    "error end odo": "لا يمكن أن يكون عداد النهاية أقل من عداد البداية.",
    "error select vehicle": "يرجى تحديد مركبة.",

    // Driver history
    "trip history": "سجل الرحلات",
    "trip history desc": "عرض جميع رحلاتك المسجلة مسبقاً.",
    "no trips": "لم تسجّل أي رحلات بعد.",
    "start odo": "عداد البداية",
    "end odo": "عداد النهاية",

    // Reports
    "reports exports": "التقارير والصادرات",
    "reports desc": "تصفح وتصفية وتنزيل سجلات الأسطول.",
    "trip logs": "سجلات الرحلات",
    "all vehicles": "جميع المركبات",
    "from date": "من",
    "to date": "إلى",
    clear: "مسح",
    excel: "Excel",
    pdf: "PDF",
    "no trip records": "لا توجد سجلات رحلات تطابق الفلاتر.",
    "no maint records": "لا توجد سجلات صيانة تطابق الفلاتر.",
    plate: "اللوحة",
    "type col": "النوع",
    "start odo col": "عداد البداية",
    "end odo col": "عداد النهاية",
    distance: "المسافة",
    "failed export": "فشل التصدير.",
    download: "تحميل",

    // Behavior
    behavior: "سلوك القيادة",
    "behavior desc": "ذكاء أداء القيادة وسلامة المركبات.",
    "fleet behavior": "ذكاء سلوك الأسطول",
    scoreboard: "لوحة أداء المركبات",
    score: "الدرجة",
    "total km": "إجمالي الكيلومترات",
    braking: "الفرملة",
    acceleration: "التسارع",
    cornering: "الانعطاف",
    speeding: "السرعة",
    violations: "المخالفات",
    "violation type": "نوع المخالفة",
    "all types": "جميع الأنواع",
    "risk level": "مستوى المخاطر",
    "high risk": "مخاطر عالية",
    "medium risk": "مخاطر متوسطة",
    "low risk": "مخاطر منخفضة",
    "upload csv": "رفع ملف CSV",
    "export behavior": "تصدير بيانات السلوك",
    "most frequent violation": "المخالفة الأكثر تكراراً",
    "avg fleet score": "متوسط درجة الأسطول",
    "high risk vehicles": "المركبات عالية المخاطر",
    "csv upload success": "تم رفع البيانات وإزالة التكرار بنجاح!",
    "csv upload failed": "فشل معالجة ملف CSV.",
    "rows per page": "عدد الصفوف",
    prev: "السابق",
    next: "التالي",
    "violation distribution": "توزيع المخالفات",
    "violation trends": "اتجاهات المخالفات",
    "performance profile": "ملف أداء الأسطول",
  },

  ur: {
    // Nav
    dashboard: "ڈیش بورڈ",
    users: "صارفین",
    vehicles: "گاڑیاں",
    maintenance: "دیکھ بھال",
    reports: "رپورٹس",
    settings: "ترتیبات",
    "sign out": "لاگ آؤٹ",
    "fmac fleet": "FMAC Fleet",

    // Language
    language: "زبان",
    "language desc": "ڈیش بورڈ انٹرفیس کی زبان منتخب کریں۔",
    "ltr layout": "بائیں سے دائیں ترتیب",
    "rtl layout": "دائیں سے بائیں ترتیب",

    // System/Settings
    "system settings": "سسٹم کی ترتیبات",
    "save changes": "تبدیلیاں محفوظ کریں",
    saving: "محفوظ ہو رہا ہے...",
    "profile settings": "پروفائل کی ترتیبات",
    "full name": "پورا نام",
    "email address": "ای میل پتہ",
    "name synced": "آپ کا نام آپ کے اکاؤنٹ سے ہم آہنگ ہے۔",
    "primary email": "آپ کا بنیادی رابطہ ای میل۔",
    role: "کردار",
    notifications: "اطلاعات",
    cancel: "منسوخ کریں",
    administrator: "منتظم",
    driver: "ڈرائیور",

    // Auth
    "sign in title": "اپنے اکاؤنٹ میں لاگ ان کریں",
    "welcome back": "خوش آمدید",
    "login desc": "اسطول تک رسائی کے لیے اپنی اسناد درج کریں۔",
    email: "ای میل",
    password: "پاس ورڈ",
    "confirm password": "پاس ورڈ کی تصدیق کریں",
    "signing in": "لاگ ان ہو رہے ہیں...",
    "sign in": "لاگ ان کریں",
    "no account": "کوئی اکاؤنٹ نہیں ہے؟",
    "sign up": "سائن اپ کریں",
    "already account": "پہلے سے اکاؤنٹ ہے؟",
    "log in": "لاگ ان کریں",
    register: "رجسٹر کریں",
    "register desc": "اسطول تک رسائی کے لیے تفصیلات درج کریں۔",
    creating: "بن رہا ہے...",
    "create account": "اکاؤنٹ بنائیں",
    "preferred language": "پسندیدہ زبان",
    "preferred language desc": "ہر بار لاگ ان کرنے پر آپ کی زبان کی ترجیح لاگو ہوگی۔",
    "password min 6": "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔",
    "passwords no match": "پاس ورڈ ایک جیسے نہیں ہیں۔",
    "invalid credentials": "غلط ای میل یا پاس ورڈ۔",

    // Vehicles
    "fleet vehicles": "اسطول گاڑیاں",
    "fleet vehicles desc": "کمپنی کی گاڑیوں اور بسوں کا انتظام کریں۔",
    "register vehicle": "نئی گاڑی درج کریں",
    "register vehicle desc": "اسطول میں گاڑی شامل کرنے کے لیے تفصیلات درج کریں۔",
    "add vehicle": "گاڑی شامل کریں",
    "save vehicle": "گاڑی محفوظ کریں",
    "plate number": "پلیٹ نمبر",
    "make and model": "میک اور ماڈل",
    "vehicle type": "گاڑی کی قسم",
    "initial odometer": "ابتدائی اوڈومیٹر (کلومیٹر)",
    status: "حیثیت",
    odometer: "اوڈومیٹر",
    actions: "اقدامات",
    active: "فعال",
    "in maintenance": "دیکھ بھال میں",
    "out of service": "سروس سے باہر",
    "no vehicles": "ابھی تک کوئی گاڑی رجسٹر نہیں ہوئی۔",
    "delete vehicle confirm": "کیا آپ واقعی اس گاڑی کو حذف کرنا چاہتے ہیں؟ یہ ناقابل واپسی ہے۔",
    "failed add vehicle": "گاڑی شامل کرنا ناکام ہوا (پلیٹ نمبر منفرد نہ ہو)۔",
    "failed delete": "حذف کرنا ناکام ہوا۔",
    "failed update status": "حیثیت اپ ڈیٹ کرنا ناکام ہوا۔",
    "failed update odometer": "اوڈومیٹر اپ ڈیٹ کرنا ناکام ہوا۔",
    "edit odometer prompt": "درست اوڈومیٹر ریڈنگ درج کریں (کلومیٹر):",
    "invalid odometer": "براہ کرم ایک درست مثبت نمبر درج کریں۔",
    "type car": "گاڑی",
    "type bus": "بس",
    "bus id": "بس آئی ڈی",
    "last driven by": "آخری ڈرائیور",

    // Maintenance
    "maintenance records": "دیکھ بھال اور ریکارڈ",
    "maintenance records desc": "اصلاحی اقدامات اور ماہانہ بلنگ۔",
    "maintenance logs": "دیکھ بھال کے لاگز",
    "monthly statements": "ماہانہ بیانات",
    "log maintenance": "سروسنگ لاگ کریں",
    "log maint entry": "دیکھ بھال کا اندراج",
    "log maint desc": "گاڑی پر کی گئی اصلاحی دیکھ بھال ریکارڈ کریں۔",
    "select vehicle": "گاڑی منتخب کریں",
    "select vehicle placeholder": "-- گاڑی منتخب کریں --",
    "description of work": "کام کی تفصیل",
    "cost optional": "لاگت (اختیاری)",
    "save log": "لاگ محفوظ کریں اور الرٹ بھیجیں",
    "upload statement": "بیان اپ لوڈ کریں",
    "upload monthly": "ماہانہ بیان اپ لوڈ کریں",
    "upload monthly desc": "گیراج سے PDF بلیں محفوظ کریں۔",
    "month year": "مہینہ / سال",
    "statement file": "بیان فائل (PDF/Excel)",
    "upload file": "فائل اپ لوڈ کریں",
    "no maintenance": "کوئی دیکھ بھال لاگ نہیں ملا۔",
    "no statements": "کوئی بیان اپ لوڈ نہیں ہوا۔",
    date: "تاریخ",
    vehicle: "گاڑی",
    cost: "لاگت",
    "failed create record": "ریکارڈ بنانے میں ناکامی۔",
    "failed upload": "بیان اپ لوڈ ناکام ہوا۔",

    // Users
    "user management": "صارف کا انتظام",
    "user management desc": "نئے سائن اپ کی منظوری دیں اور مراعات تفویض کریں۔",
    user: "صارف",
    contact: "رابطہ",
    joined: "شامل ہونے کی تاریخ",
    "status col": "حیثیت",
    "role col": "کردار",
    "access control": "رسائی کنٹرول",
    approved: "منظور شدہ",
    pending: "زیر التواء",
    "pending approval": "منظوری زیر التوا ہے",
    "pending desc": "آپ کا اکاؤنٹ بن گیا ہے اور ایڈمنسٹریٹر کی منظوری کا منتظر ہے۔ اپنی رسائی کو فعال کرنے کے لیے براہ کرم اپنے بیڑے کے مینیجر سے رابطہ کریں۔",
    "refresh status": "حالت کو تازہ کریں",
    approve: "منظور کریں",
    revoke: "رسائی منسوخ کریں",
    "no users": "کوئی صارف نہیں ملا۔",
    you: "آپ",
    "role change confirm": "کیا آپ واقعی اس صارف کا کردار تبدیل کرنا چاہتے ہیں",

    // Dashboard
    overview: "جائزہ",
    "overview desc": "FMAC اسطول کے لیے ریئل ٹائم میٹرکس۔",
    "total vehicles": "کل گاڑیاں",
    "vehicles active": "فعال",
    "in maintenance count": "دیکھ بھال میں",
    "requires attention": "توجہ کی ضرورت ہے",
    "out of service count": "سروس سے باہر",
    "inactive vehicles": "غیر فعال گاڑیاں",
    "distance 7d": "فاصلہ (7 دن)",
    "across all": "تمام فعال گاڑیوں میں",
    "mileage trend": "مائلج ٹرینڈ",
    "mileage trend desc": "گزشتہ 7 دنوں میں طے شدہ فاصلہ",
    "recent activity": "حالیہ سرگرمی",
    "no recent activity": "کوئی حالیہ سرگرمی نہیں۔",
    "trip logged": "سفر درج ہوا",
    "maintenance recorded": "دیکھ بھال درج ہوئی",
    "unknown vehicle": "نامعلوم گاڑی",

    // Driver dashboard
    "log new trip": "نیا سفر درج کریں",
    "log new trip desc": "گاڑی منتخب کریں اور سفر کی تفصیلات درج کریں۔",
    "trip details": "سفر کی تفصیلات",
    "trip details desc": "نوٹس کے علاوہ تمام خانے ضروری ہیں۔",
    "trip type": "سفر کی قسم",
    "internal trip": "اندرونی (کلب ٹرانسپورٹ)",
    "external trip": "بیرونی (ٹورنامنٹ/تقریبات)",
    "start odometer": "ابتدائی اوڈومیٹر",
    "end odometer": "اختتامی اوڈومیٹر",
    "calculated distance": "حساب شدہ فاصلہ:",
    "notes optional": "نوٹس (اختیاری)",
    "notes placeholder": "منزل، مقصد، یا مسائل...",
    submitting: "جمع ہو رہا ہے...",
    "submit trip": "سفر لاگ جمع کریں",
    "trip success": "سفر کامیابی سے درج ہوا!",
    "error end odo": "اختتامی اوڈومیٹر ابتدائی سے کم نہیں ہو سکتا۔",
    "error select vehicle": "براہ کرم ایک گاڑی منتخب کریں۔",

    // Driver history
    "trip history": "سفر کی تاریخ",
    "trip history desc": "اپنے تمام پہلے درج شدہ سفر دیکھیں۔",
    "no trips": "آپ نے ابھی تک کوئی سفر درج نہیں کیا۔",
    "start odo": "ابتدائی اوڈومیٹر",
    "end odo": "اختتامی اوڈومیٹر",

    // Reports
    "reports exports": "رپورٹس اور برآمد",
    "reports desc": "اسطول کے ریکارڈ براؤز، فلٹر اور ڈاؤن لوڈ کریں۔",
    "trip logs": "سفر کے لاگز",
    "all vehicles": "تمام گاڑیاں",
    "from date": "سے",
    "to date": "تک",
    clear: "صاف کریں",
    excel: "ایکسل",
    pdf: "پی ڈی ایف",
    "no trip records": "کوئی سفر ریکارڈ فلٹر سے مطابقت نہیں رکھتا۔",
    "no maint records": "کوئی دیکھ بھال ریکارڈ فلٹر سے مطابقت نہیں رکھتا۔",
    plate: "پلیٹ",
    "type col": "قسم",
    "start odo col": "ابتدائی اوڈومیٹر",
    "end odo col": "اختتامی اوڈومیٹر",
    distance: "فاصلہ",
    "failed export": "برآمد ناکام ہوا۔",
    download: "ڈاؤن لوڈ",

    // Behavior
    behavior: "ڈرائیونگ کا رویہ",
    "behavior desc": "گاڑی چلانے کی کارکردگی اور حفاظتی معلومات۔",
    "fleet behavior": "اسطول کے رویے کی معلومات",
    scoreboard: "وہیکل اسکور بورڈ",
    score: "اسکور",
    "total km": "کل کلومیٹر",
    braking: "بریک لگانا",
    acceleration: "تیزی",
    cornering: "موڑ کاٹنا",
    speeding: "تیز رفتاری",
    violations: "خلاف ورزیاں",
    "violation type": "خلاف ورزی کی قسم",
    "all types": "تمام اقسام",
    "risk level": "خطرہ کی سطح",
    "high risk": "اعلی خطرہ",
    "medium risk": "درمیانہ خطرہ",
    "low risk": "کم خطرہ",
    "upload csv": "CSV اپ لوڈ کریں",
    "export behavior": "رویے کا ڈیٹا برآمد کریں",
    "most frequent violation": "اسکور کا اوسط اسکور",
    "avg fleet score": "اسطول کا اوسط اسکور",
    "high risk vehicles": "اعلی خطرناک گاڑیاں",
    "csv upload success": "ڈیٹا کامیابی سے اپ لوڈ اور صاف کر دیا گیا!",
    "csv upload failed": "CSV فائل پر کارروائی کرنے میں ناکامی۔",
    "rows per page": "فی صفحہ قطاریں",
    prev: "پچھلا",
    next: "اگلا",
    "violation distribution": "خلاف ورزیوں کی تقسیم",
    "violation trends": "خلاف ورزیوں کے رجحانات",
    "performance profile": "اسطول کی کارکردگی کا پروفائل",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("fmac_language") as Language;
    if (savedLang && ["en", "ar", "ur"].includes(savedLang)) {
      setLanguageState(savedLang);
    }
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    document.documentElement.dir = language === "en" ? "ltr" : "rtl";
    document.documentElement.lang = language;
    localStorage.setItem("fmac_language", language);
  }, [language, mounted]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const defaultText = translations.en[key] || key;
    if (!mounted) return defaultText;
    return translations[language][key] || defaultText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={mounted ? (language === "en" ? "ltr" : "rtl") : "ltr"} className="contents">
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
