"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "ar" | "ur";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Language names always in their own native script — never translated
export const NATIVE_LANGUAGE_NAMES: Record<Language, string> = {
  en: "English",
  ar: "العربية",
  ur: "اردو",
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    dashboard: "Dashboard",
    users: "Users",
    vehicles: "Vehicles",
    maintenance: "Maintenance",
    reports: "Reports",
    settings: "Settings",
    sign_out: "Sign out",
    // FMAC branding — never translated
    fmac_fleet: "FMAC Fleet",

    // Language
    language: "Language",
    language_desc: "Select the language for the dashboard interface.",
    ltr_layout: "LTR Layout",
    rtl_layout: "RTL Layout",

    // System/Settings
    system_settings: "System Settings",
    save_changes: "Save Changes",
    saving: "Saving...",
    profile_settings: "Profile Settings",
    full_name: "Full Name",
    email_address: "Email Address",
    name_synced: "Your name is synchronized with your account.",
    primary_email: "Your primary contact email.",
    role: "Role",
    notifications: "Notifications",
    cancel: "Cancel",
    administrator: "Administrator",
    driver: "Driver",

    // Auth
    sign_in_title: "Sign in to your account",
    welcome_back: "Welcome back",
    login_desc: "Enter your credentials to access the fleet.",
    email: "Email",
    password: "Password",
    confirm_password: "Confirm Password",
    signing_in: "Signing in...",
    sign_in: "Sign in",
    no_account: "Don't have an account?",
    sign_up: "Sign up",
    already_account: "Already have an account?",
    log_in: "Log in",
    register: "Register",
    register_desc: "Enter details to request fleet access.",
    creating: "Creating...",
    create_account: "Create Account",
    preferred_language: "Preferred Language",
    preferred_language_desc: "Your language preference will be applied each time you log in.",
    password_min_6: "Password must be at least 6 characters.",
    passwords_no_match: "Passwords do not match.",
    invalid_credentials: "Invalid email or password.",

    // Vehicles
    fleet_vehicles: "Fleet Vehicles",
    fleet_vehicles_desc: "Manage company cars and buses.",
    register_vehicle: "Register New Vehicle",
    register_vehicle_desc: "Enter details to add a vehicle to the fleet.",
    add_vehicle: "Add Vehicle",
    save_vehicle: "Save Vehicle",
    plate_number: "Plate Number",
    make_and_model: "Make & Model",
    vehicle_type: "Vehicle Type",
    initial_odometer: "Initial Odometer (km)",
    status: "Status",
    odometer: "Odometer",
    actions: "Actions",
    active: "Active",
    in_maintenance: "In Maintenance",
    out_of_service: "Out of Service",
    no_vehicles: "No vehicles registered yet.",
    delete_vehicle_confirm: "Are you sure you want to delete this vehicle? Actions cannot be undone.",
    failed_add_vehicle: "Failed to add vehicle (Plate number might not be unique).",
    failed_delete: "Failed to delete.",
    failed_update_status: "Failed to update status.",
    failed_update_odometer: "Failed to update odometer.",
    edit_odometer_prompt: "Enter the correct odometer reading (km):",
    invalid_odometer: "Please enter a valid positive number.",
    type_car: "Car",
    type_bus: "Bus",

    // Maintenance
    maintenance_records: "Maintenance & Records",
    maintenance_records_desc: "Corrective actions and monthly billing.",
    maintenance_logs: "Maintenance Logs",
    monthly_statements: "Monthly Statements",
    log_maintenance: "Log Servicing",
    log_maint_entry: "Log Maintenance Entry",
    log_maint_desc: "Record corrective maintenance performed on a vehicle.",
    select_vehicle: "Select Vehicle",
    select_vehicle_placeholder: "-- Select a vehicle --",
    description_of_work: "Description of Work",
    cost_optional: "Cost (Optional)",
    save_log: "Save Log & Send Alert",
    upload_statement: "Upload Statement",
    upload_monthly: "Upload Monthly Statement",
    upload_monthly_desc: "Archive PDF bills from the garage.",
    month_year: "Month / Year",
    statement_file: "Statement File (PDF/Excel)",
    upload_file: "Upload File",
    no_maintenance: "No maintenance logs found.",
    no_statements: "No statements uploaded.",
    date: "Date",
    vehicle: "Vehicle",
    cost: "Cost",
    failed_create_record: "Failed to create record.",
    failed_upload: "Failed to upload statement.",

    // Users
    user_management: "User Management",
    user_management_desc: "Approve new signups and assign administrative privileges.",
    user: "User",
    contact: "Contact",
    joined: "Joined",
    status_col: "Status",
    role_col: "Role",
    approved: "Approved",
    pending: "Pending",
    approve: "Approve",
    revoke: "Revoke",
    no_users: "No users found.",
    you: "You",
    role_change_confirm: "Are you sure you want to change this user's role to",

    // Dashboard
    overview: "Overview",
    overview_desc: "Real-time metrics for the FMAC fleet.",
    total_vehicles: "Total Vehicles",
    vehicles_active: "Active",
    in_maintenance_count: "In Maintenance",
    requires_attention: "Requires attention",
    out_of_service_count: "Out of Service",
    inactive_vehicles: "Inactive vehicles",
    distance_7d: "Distance (7d)",
    across_all: "Across all active vehicles",
    mileage_trend: "Mileage Trend",
    mileage_trend_desc: "Distance traversed over the past 7 days",
    recent_activity: "Recent Activity",
    no_recent_activity: "No recent activity.",
    trip_logged: "Trip Logged",
    maintenance_recorded: "Maintenance Recorded",
    unknown_vehicle: "Unknown Vehicle",

    // Driver dashboard
    log_new_trip: "Log New Trip",
    log_new_trip_desc: "Select a vehicle and enter your post-trip details.",
    trip_details: "Trip Details",
    trip_details_desc: "All fields except notes are required.",
    trip_type: "Trip Type",
    internal_trip: "Internal (Club Transport)",
    external_trip: "External (Tournaments/Events)",
    start_odometer: "Start Odometer",
    end_odometer: "End Odometer",
    calculated_distance: "Calculated Distance:",
    notes_optional: "Notes (Optional)",
    notes_placeholder: "Destination, purpose, or issues...",
    submitting: "Submitting...",
    submit_trip: "Submit Trip Log",
    trip_success: "Trip logged successfully!",
    error_end_odo: "End odometer cannot be less than start odometer.",
    error_select_vehicle: "Please select a vehicle.",

    // Driver history
    trip_history: "Trip History",
    trip_history_desc: "View all your previously logged trips.",
    no_trips: "You haven't logged any trips yet.",
    start_odo: "Start Odo",
    end_odo: "End Odo",

    // Reports
    reports_exports: "Reports & Exports",
    reports_desc: "Browse, filter, and download fleet records.",
    trip_logs: "Trip Logs",
    all_vehicles: "All Vehicles",
    from_date: "From",
    to_date: "To",
    clear: "Clear",
    excel: "Excel",
    pdf: "PDF",
    no_trip_records: "No trip records match your filters.",
    no_maint_records: "No maintenance records match your filters.",
    plate: "Plate",
    type_col: "Type",
    start_odo_col: "Start Odo",
    end_odo_col: "End Odo",
    distance: "Distance",
    failed_export: "Failed to export.",
    download: "Download",

    // Behavior
    behavior: "Behavior",
    behavior_desc: "Vehicle driving performance and safety intelligence.",
    fleet_behavior: "Fleet Behavior Intelligence",
    scoreboard: "Vehicle Scoreboard",
    score: "Score",
    total_km: "Total KM",
    braking: "Braking",
    acceleration: "Acceleration",
    cornering: "Cornering",
    speeding: "Speeding",
    violations: "Violations",
    violation_type: "Violation Type",
    risk_level: "Risk Level",
    high_risk: "High Risk",
    medium_risk: "Medium Risk",
    low_risk: "Low Risk",
    upload_csv: "Upload CSV",
    export_behavior: "Export Behavior Data",
    most_frequent_violation: "Most Frequent Violation",
    avg_fleet_score: "Avg Fleet Score",
    high_risk_vehicles: "High Risk Vehicles",
    csv_upload_success: "Data uploaded and deduplicated successfully!",
    csv_upload_failed: "Failed to process CSV file.",
    rows_per_page: "Rows per page",
    prev: "Prev",
    next: "Next",
    violation_distribution: "Violation Distribution",
    violation_trends: "Violation Trends",
    performance_profile: "Fleet Performance Profile",
  },

  ar: {
    // Nav
    dashboard: "لوحة القيادة",
    users: "المستخدمين",
    vehicles: "المركبات",
    maintenance: "الصيانة",
    reports: "التقارير",
    settings: "الإعدادات",
    sign_out: "تسجيل الخروج",
    fmac_fleet: "FMAC Fleet",

    // Language
    language: "اللغة",
    language_desc: "اختر لغة واجهة لوحة التحكم.",
    ltr_layout: "تخطيط من اليسار لليمين",
    rtl_layout: "تخطيط من اليمين لليسار",

    // System/Settings
    system_settings: "إعدادات النظام",
    save_changes: "حفظ التغييرات",
    saving: "جارٍ الحفظ...",
    profile_settings: "إعدادات الملف الشخصي",
    full_name: "الاسم الكامل",
    email_address: "البريد الإلكتروني",
    name_synced: "اسمك متزامن مع حسابك.",
    primary_email: "بريدك الإلكتروني الأساسي.",
    role: "الدور",
    notifications: "الإشعارات",
    cancel: "إلغاء",
    administrator: "مسؤول",
    driver: "سائق",

    // Auth
    sign_in_title: "تسجيل الدخول إلى حسابك",
    welcome_back: "مرحباً بعودتك",
    login_desc: "أدخل بياناتك للوصول إلى الأسطول.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirm_password: "تأكيد كلمة المرور",
    signing_in: "جارٍ تسجيل الدخول...",
    sign_in: "تسجيل الدخول",
    no_account: "ليس لديك حساب؟",
    sign_up: "إنشاء حساب",
    already_account: "هل لديك حساب بالفعل؟",
    log_in: "تسجيل الدخول",
    register: "تسجيل",
    register_desc: "أدخل التفاصيل لطلب الوصول إلى الأسطول.",
    creating: "جارٍ الإنشاء...",
    create_account: "إنشاء حساب",
    preferred_language: "اللغة المفضلة",
    preferred_language_desc: "سيتم تطبيق تفضيل اللغة في كل مرة تسجل الدخول.",
    password_min_6: "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
    passwords_no_match: "كلمتا المرور غير متطابقتين.",
    invalid_credentials: "بريد إلكتروني أو كلمة مرور غير صحيحة.",

    // Vehicles
    fleet_vehicles: "مركبات الأسطول",
    fleet_vehicles_desc: "إدارة سيارات وحافلات الشركة.",
    register_vehicle: "تسجيل مركبة جديدة",
    register_vehicle_desc: "أدخل التفاصيل لإضافة مركبة إلى الأسطول.",
    add_vehicle: "إضافة مركبة",
    save_vehicle: "حفظ المركبة",
    plate_number: "رقم اللوحة",
    make_and_model: "الماركة والموديل",
    vehicle_type: "نوع المركبة",
    initial_odometer: "قراءة العداد الأولية (كم)",
    status: "الحالة",
    odometer: "عداد المسافة",
    actions: "الإجراءات",
    active: "نشطة",
    in_maintenance: "قيد الصيانة",
    out_of_service: "خارج الخدمة",
    no_vehicles: "لم يتم تسجيل أي مركبات بعد.",
    delete_vehicle_confirm: "هل أنت متأكد من حذف هذه المركبة؟ لا يمكن التراجع عن هذا الإجراء.",
    failed_add_vehicle: "فشل إضافة المركبة (قد يكون رقم اللوحة مكرراً).",
    failed_delete: "فشل الحذف.",
    failed_update_status: "فشل تحديث الحالة.",
    failed_update_odometer: "فشل تحديث القراءة.",
    edit_odometer_prompt: "أدخل قراءة عداد المسافة الصحيحة (كم):",
    invalid_odometer: "يرجى إدخال رقم صحيح وموجب.",
    type_car: "سيارة",
    type_bus: "حافلة",

    // Maintenance
    maintenance_records: "الصيانة والسجلات",
    maintenance_records_desc: "الإجراءات التصحيحية والفواتير الشهرية.",
    maintenance_logs: "سجلات الصيانة",
    monthly_statements: "الكشوفات الشهرية",
    log_maintenance: "تسجيل عملية صيانة",
    log_maint_entry: "إدخال سجل الصيانة",
    log_maint_desc: "تسجيل الصيانة التصحيحية التي أُجريت على مركبة.",
    select_vehicle: "اختر المركبة",
    select_vehicle_placeholder: "-- اختر مركبة --",
    description_of_work: "وصف العمل",
    cost_optional: "التكلفة (اختياري)",
    save_log: "حفظ السجل وإرسال تنبيه",
    upload_statement: "رفع كشف حساب",
    upload_monthly: "رفع كشف شهري",
    upload_monthly_desc: "أرشفة فواتير PDF من الورشة.",
    month_year: "الشهر / السنة",
    statement_file: "ملف الكشف (PDF/Excel)",
    upload_file: "رفع الملف",
    no_maintenance: "لم يتم العثور على سجلات صيانة.",
    no_statements: "لم يتم رفع أي كشوفات.",
    date: "التاريخ",
    vehicle: "المركبة",
    cost: "التكلفة",
    failed_create_record: "فشل إنشاء السجل.",
    failed_upload: "فشل رفع الكشف.",

    // Users
    user_management: "إدارة المستخدمين",
    user_management_desc: "الموافقة على التسجيلات الجديدة وتعيين الصلاحيات.",
    user: "المستخدم",
    contact: "التواصل",
    joined: "تاريخ الانضمام",
    status_col: "الحالة",
    role_col: "الدور",
    approved: "موافق عليه",
    pending: "قيد الانتظار",
    approve: "موافقة",
    revoke: "إلغاء الوصول",
    no_users: "لم يتم العثور على مستخدمين.",
    you: "أنت",
    role_change_confirm: "هل أنت متأكد من تغيير دور هذا المستخدم إلى",

    // Dashboard
    overview: "نظرة عامة",
    overview_desc: "مقاييس فورية لأسطول FMAC.",
    total_vehicles: "إجمالي المركبات",
    vehicles_active: "نشطة",
    in_maintenance_count: "قيد الصيانة",
    requires_attention: "تحتاج إلى اهتمام",
    out_of_service_count: "خارج الخدمة",
    inactive_vehicles: "مركبات غير نشطة",
    distance_7d: "المسافة (7 أيام)",
    across_all: "عبر جميع المركبات النشطة",
    mileage_trend: "اتجاه المسافة",
    mileage_trend_desc: "المسافة المقطوعة خلال الـ7 أيام الماضية",
    recent_activity: "النشاط الأخير",
    no_recent_activity: "لا يوجد نشاط أخير.",
    trip_logged: "تم تسجيل رحلة",
    maintenance_recorded: "تم تسجيل صيانة",
    unknown_vehicle: "مركبة غير معروفة",

    // Driver dashboard
    log_new_trip: "تسجيل رحلة جديدة",
    log_new_trip_desc: "اختر المركبة وأدخل تفاصيل الرحلة.",
    trip_details: "تفاصيل الرحلة",
    trip_details_desc: "جميع الحقول مطلوبة ما عدا الملاحظات.",
    trip_type: "نوع الرحلة",
    internal_trip: "داخلية (نقل النادي)",
    external_trip: "خارجية (بطولات/فعاليات)",
    start_odometer: "عداد البداية",
    end_odometer: "عداد النهاية",
    calculated_distance: "المسافة المحسوبة:",
    notes_optional: "ملاحظات (اختياري)",
    notes_placeholder: "الوجهة، الغرض، أو المشكلات...",
    submitting: "جارٍ الإرسال...",
    submit_trip: "إرسال سجل الرحلة",
    trip_success: "تم تسجيل الرحلة بنجاح!",
    error_end_odo: "لا يمكن أن يكون عداد النهاية أقل من عداد البداية.",
    error_select_vehicle: "يرجى تحديد مركبة.",

    // Driver history
    trip_history: "سجل الرحلات",
    trip_history_desc: "عرض جميع رحلاتك المسجلة مسبقاً.",
    no_trips: "لم تسجّل أي رحلات بعد.",
    start_odo: "عداد البداية",
    end_odo: "عداد النهاية",

    // Reports
    reports_exports: "التقارير والصادرات",
    reports_desc: "تصفح وتصفية وتنزيل سجلات الأسطول.",
    trip_logs: "سجلات الرحلات",
    all_vehicles: "جميع المركبات",
    from_date: "من",
    to_date: "إلى",
    clear: "مسح",
    excel: "Excel",
    pdf: "PDF",
    no_trip_records: "لا توجد سجلات رحلات تطابق الفلاتر.",
    no_maint_records: "لا توجد سجلات صيانة تطابق الفلاتر.",
    plate: "اللوحة",
    type_col: "النوع",
    start_odo_col: "عداد البداية",
    end_odo_col: "عداد النهاية",
    distance: "المسافة",
    failed_export: "فشل التصدير.",
    download: "تحميل",

    // Behavior
    behavior: "سلوك القيادة",
    behavior_desc: "ذكاء أداء القيادة وسلامة المركبات.",
    fleet_behavior: "ذكاء سلوك الأسطول",
    scoreboard: "لوحة أداء المركبات",
    score: "الدرجة",
    total_km: "إجمالي الكيلومترات",
    braking: "الفرملة",
    acceleration: "التسارع",
    cornering: "الانعطاف",
    speeding: "السرعة",
    violations: "المخالفات",
    violation_type: "نوع المخالفة",
    risk_level: "مستوى المخاطر",
    high_risk: "مخاطر عالية",
    medium_risk: "مخاطر متوسطة",
    low_risk: "مخاطر منخفضة",
    upload_csv: "رفع ملف CSV",
    export_behavior: "تصدير بيانات السلوك",
    most_frequent_violation: "المخالفة الأكثر تكراراً",
    avg_fleet_score: "متوسط درجة الأسطول",
    high_risk_vehicles: "المركبات عالية المخاطر",
    csv_upload_success: "تم رفع البيانات وإزالة التكرار بنجاح!",
    csv_upload_failed: "فشل معالجة ملف CSV.",
    rows_per_page: "عدد الصفوف",
    prev: "السابق",
    next: "التالي",
    violation_distribution: "توزيع المخالفات",
    violation_trends: "اتجاهات المخالفات",
    performance_profile: "ملف أداء الأسطول",
  },

  ur: {
    // Nav
    dashboard: "ڈیش بورڈ",
    users: "صارفین",
    vehicles: "گاڑیاں",
    maintenance: "دیکھ بھال",
    reports: "رپورٹس",
    settings: "ترتیبات",
    sign_out: "لاگ آؤٹ",
    fmac_fleet: "FMAC Fleet",

    // Language
    language: "زبان",
    language_desc: "ڈیش بورڈ انٹرفیس کی زبان منتخب کریں۔",
    ltr_layout: "بائیں سے دائیں ترتیب",
    rtl_layout: "دائیں سے بائیں ترتیب",

    // System/Settings
    system_settings: "سسٹم کی ترتیبات",
    save_changes: "تبدیلیاں محفوظ کریں",
    saving: "محفوظ ہو رہا ہے...",
    profile_settings: "پروفائل کی ترتیبات",
    full_name: "پورا نام",
    email_address: "ای میل پتہ",
    name_synced: "آپ کا نام آپ کے اکاؤنٹ سے ہم آہنگ ہے۔",
    primary_email: "آپ کا بنیادی رابطہ ای میل۔",
    role: "کردار",
    notifications: "اطلاعات",
    cancel: "منسوخ کریں",
    administrator: "منتظم",
    driver: "ڈرائیور",

    // Auth
    sign_in_title: "اپنے اکاؤنٹ میں لاگ ان کریں",
    welcome_back: "خوش آمدید",
    login_desc: "اسطول تک رسائی کے لیے اپنی اسناد درج کریں۔",
    email: "ای میل",
    password: "پاس ورڈ",
    confirm_password: "پاس ورڈ کی تصدیق کریں",
    signing_in: "لاگ ان ہو رہے ہیں...",
    sign_in: "لاگ ان کریں",
    no_account: "کوئی اکاؤنٹ نہیں ہے؟",
    sign_up: "سائن اپ کریں",
    already_account: "پہلے سے اکاؤنٹ ہے؟",
    log_in: "لاگ ان کریں",
    register: "رجسٹر کریں",
    register_desc: "اسطول تک رسائی کے لیے تفصیلات درج کریں۔",
    creating: "بن رہا ہے...",
    create_account: "اکاؤنٹ بنائیں",
    preferred_language: "پسندیدہ زبان",
    preferred_language_desc: "ہر بار لاگ ان کرنے پر آپ کی زبان کی ترجیح لاگو ہوگی۔",
    password_min_6: "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔",
    passwords_no_match: "پاس ورڈ ایک جیسے نہیں ہیں۔",
    invalid_credentials: "غلط ای میل یا پاس ورڈ۔",

    // Vehicles
    fleet_vehicles: "اسطول گاڑیاں",
    fleet_vehicles_desc: "کمپنی کی گاڑیوں اور بسوں کا انتظام کریں۔",
    register_vehicle: "نئی گاڑی درج کریں",
    register_vehicle_desc: "اسطول میں گاڑی شامل کرنے کے لیے تفصیلات درج کریں۔",
    add_vehicle: "گاڑی شامل کریں",
    save_vehicle: "گاڑی محفوظ کریں",
    plate_number: "پلیٹ نمبر",
    make_and_model: "میک اور ماڈل",
    vehicle_type: "گاڑی کی قسم",
    initial_odometer: "ابتدائی اوڈومیٹر (کلومیٹر)",
    status: "حیثیت",
    odometer: "اوڈومیٹر",
    actions: "اقدامات",
    active: "فعال",
    in_maintenance: "دیکھ بھال میں",
    out_of_service: "سروس سے باہر",
    no_vehicles: "ابھی تک کوئی گاڑی رجسٹر نہیں ہوئی۔",
    delete_vehicle_confirm: "کیا آپ واقعی اس گاڑی کو حذف کرنا چاہتے ہیں؟ یہ ناقابل واپسی ہے۔",
    failed_add_vehicle: "گاڑی شامل کرنا ناکام ہوا (پلیٹ نمبر منفرد نہ ہو)۔",
    failed_delete: "حذف کرنا ناکام ہوا۔",
    failed_update_status: "حیثیت اپ ڈیٹ کرنا ناکام ہوا۔",
    failed_update_odometer: "اوڈومیٹر اپ ڈیٹ کرنا ناکام ہوا۔",
    edit_odometer_prompt: "درست اوڈومیٹر ریڈنگ درج کریں (کلومیٹر):",
    invalid_odometer: "براہ کرم ایک درست مثبت نمبر درج کریں۔",
    type_car: "گاڑی",
    type_bus: "بس",

    // Maintenance
    maintenance_records: "دیکھ بھال اور ریکارڈ",
    maintenance_records_desc: "اصلاحی اقدامات اور ماہانہ بلنگ۔",
    maintenance_logs: "دیکھ بھال کے لاگز",
    monthly_statements: "ماہانہ بیانات",
    log_maintenance: "سروسنگ لاگ کریں",
    log_maint_entry: "دیکھ بھال کا اندراج",
    log_maint_desc: "گاڑی پر کی گئی اصلاحی دیکھ بھال ریکارڈ کریں۔",
    select_vehicle: "گاڑی منتخب کریں",
    select_vehicle_placeholder: "-- گاڑی منتخب کریں --",
    description_of_work: "کام کی تفصیل",
    cost_optional: "لاگت (اختیاری)",
    save_log: "لاگ محفوظ کریں اور الرٹ بھیجیں",
    upload_statement: "بیان اپ لوڈ کریں",
    upload_monthly: "ماہانہ بیان اپ لوڈ کریں",
    upload_monthly_desc: "گیراج سے PDF بلیں محفوظ کریں۔",
    month_year: "مہینہ / سال",
    statement_file: "بیان فائل (PDF/Excel)",
    upload_file: "فائل اپ لوڈ کریں",
    no_maintenance: "کوئی دیکھ بھال لاگ نہیں ملا۔",
    no_statements: "کوئی بیان اپ لوڈ نہیں ہوا۔",
    date: "تاریخ",
    vehicle: "گاڑی",
    cost: "لاگت",
    failed_create_record: "ریکارڈ بنانے میں ناکامی۔",
    failed_upload: "بیان اپ لوڈ ناکام ہوا۔",

    // Users
    user_management: "صارف کا انتظام",
    user_management_desc: "نئے سائن اپ کی منظوری دیں اور مراعات تفویض کریں۔",
    user: "صارف",
    contact: "رابطہ",
    joined: "شامل ہونے کی تاریخ",
    status_col: "حیثیت",
    role_col: "کردار",
    approved: "منظور شدہ",
    pending: "زیر التواء",
    approve: "منظور کریں",
    revoke: "رسائی منسوخ کریں",
    no_users: "کوئی صارف نہیں ملا۔",
    you: "آپ",
    role_change_confirm: "کیا آپ واقعی اس صارف کا کردار تبدیل کرنا چاہتے ہیں",

    // Dashboard
    overview: "جائزہ",
    overview_desc: "FMAC اسطول کے لیے ریئل ٹائم میٹرکس۔",
    total_vehicles: "کل گاڑیاں",
    vehicles_active: "فعال",
    in_maintenance_count: "دیکھ بھال میں",
    requires_attention: "توجہ کی ضرورت ہے",
    out_of_service_count: "سروس سے باہر",
    inactive_vehicles: "غیر فعال گاڑیاں",
    distance_7d: "فاصلہ (7 دن)",
    across_all: "تمام فعال گاڑیوں میں",
    mileage_trend: "مائلج ٹرینڈ",
    mileage_trend_desc: "گزشتہ 7 دنوں میں طے شدہ فاصلہ",
    recent_activity: "حالیہ سرگرمی",
    no_recent_activity: "کوئی حالیہ سرگرمی نہیں۔",
    trip_logged: "سفر درج ہوا",
    maintenance_recorded: "دیکھ بھال درج ہوئی",
    unknown_vehicle: "نامعلوم گاڑی",

    // Driver dashboard
    log_new_trip: "نیا سفر درج کریں",
    log_new_trip_desc: "گاڑی منتخب کریں اور سفر کی تفصیلات درج کریں۔",
    trip_details: "سفر کی تفصیلات",
    trip_details_desc: "نوٹس کے علاوہ تمام خانے ضروری ہیں۔",
    trip_type: "سفر کی قسم",
    internal_trip: "اندرونی (کلب ٹرانسپورٹ)",
    external_trip: "بیرونی (ٹورنامنٹ/تقریبات)",
    start_odometer: "ابتدائی اوڈومیٹر",
    end_odometer: "اختتامی اوڈومیٹر",
    calculated_distance: "حساب شدہ فاصلہ:",
    notes_optional: "نوٹس (اختیاری)",
    notes_placeholder: "منزل، مقصد، یا مسائل...",
    submitting: "جمع ہو رہا ہے...",
    submit_trip: "سفر لاگ جمع کریں",
    trip_success: "سفر کامیابی سے درج ہوا!",
    error_end_odo: "اختتامی اوڈومیٹر ابتدائی سے کم نہیں ہو سکتا۔",
    error_select_vehicle: "براہ کرم ایک گاڑی منتخب کریں۔",

    // Driver history
    trip_history: "سفر کی تاریخ",
    trip_history_desc: "اپنے تمام پہلے درج شدہ سفر دیکھیں۔",
    no_trips: "آپ نے ابھی تک کوئی سفر درج نہیں کیا۔",
    start_odo: "ابتدائی اوڈومیٹر",
    end_odo: "اختتامی اوڈومیٹر",

    // Reports
    reports_exports: "رپورٹس اور برآمد",
    reports_desc: "اسطول کے ریکارڈ براؤز، فلٹر اور ڈاؤن لوڈ کریں۔",
    trip_logs: "سفر کے لاگز",
    all_vehicles: "تمام گاڑیاں",
    from_date: "سے",
    to_date: "تک",
    clear: "صاف کریں",
    excel: "ایکسل",
    pdf: "پی ڈی ایف",
    no_trip_records: "کوئی سفر ریکارڈ فلٹر سے مطابقت نہیں رکھتا۔",
    no_maint_records: "کوئی دیکھ بھال ریکارڈ فلٹر سے مطابقت نہیں رکھتا۔",
    plate: "پلیٹ",
    type_col: "قسم",
    start_odo_col: "ابتدائی اوڈومیٹر",
    end_odo_col: "اختتامی اوڈومیٹر",
    distance: "فاصلہ",
    failed_export: "برآمد ناکام ہوا۔",
    download: "ڈاؤن لوڈ",

    // Behavior
    behavior: "ڈرائیونگ کا رویہ",
    behavior_desc: "گاڑی چلانے کی کارکردگی اور حفاظتی معلومات۔",
    fleet_behavior: "اسطول کے رویے کی معلومات",
    scoreboard: "وہیکل اسکور بورڈ",
    score: "اسکور",
    total_km: "کل کلومیٹر",
    braking: "بریک لگانا",
    acceleration: "تیزی",
    cornering: "موڑ کاٹنا",
    speeding: "تیز رفتاری",
    violations: "خلاف ورزیاں",
    violation_type: "خلاف ورزی کی قسم",
    risk_level: "خطرہ کی سطح",
    high_risk: "اعلی خطرہ",
    medium_risk: "درمیانہ خطرہ",
    low_risk: "کم خطرہ",
    upload_csv: "CSV اپ لوڈ کریں",
    export_behavior: "رویے کا ڈیٹا برآمد کریں",
    most_frequent_violation: "سب سے زیادہ بار ہونے والی خلاف ورزی",
    avg_fleet_score: "اسطول کا اوسط اسکور",
    high_risk_vehicles: "اعلی خطرناک گاڑیاں",
    csv_upload_success: "ڈیٹا کامیابی سے اپ لوڈ اور صاف کر دیا گیا!",
    csv_upload_failed: "CSV فائل پر کارروائی کرنے میں ناکامی۔",
    rows_per_page: "فی صفحہ قطاریں",
    prev: "پچھلا",
    next: "اگلا",
    violation_distribution: "خلاف ورزیوں کی تقسیم",
    violation_trends: "خلاف ورزیوں کے رجحانات",
    performance_profile: "اسطول کی کارکردگی کا پروفائل",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("fmac_language") as Language;
    if (savedLang && ["en", "ar", "ur"].includes(savedLang)) {
      setLanguageState(savedLang);
    }
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    document.documentElement.dir = language === "en" ? "ltr" : "rtl";
    document.documentElement.lang = language;
    localStorage.setItem("fmac_language", language);
  }, [language, mounted]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const defaultText = translations.en[key] || key;
    if (!mounted) return defaultText;
    return translations[language][key] || defaultText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={mounted ? (language === "en" ? "ltr" : "rtl") : "ltr"} className="contents">
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
